name: README

on:
    push:
        branches: [main]
        paths:
            - "data/*"

    workflow_dispatch: {}

jobs:
    update:
        name: Update
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3

            - name: Update README
              run: |
                  chmod +x scripts/update-readme.sh
                  ./scripts/update-readme.sh

            - name: Sleep for 30 seconds
              run: sleep 30

            - name: Commit
              run: |
                  git config --global user.email "actions@github.com"
                  git config --global user.name "GitHub Actions"
                  git add README.md
                  git pull
                  git commit -m "chore: update readme"
                  git push
