name: RSS Feed

on:
    push:
        branches: [main]
        paths:
            - "data/*"

    workflow_dispatch: {}

permissions:
    contents: write

jobs:
    generate:
        name: Generate
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-python@v5
              with:
                  python-version: 3.11
                  cache: pip
                  cache-dependency-path: scripts/rss/requirements.txt

            - name: Install Dependencies
              run: pip install -r scripts/rss/requirements.txt

            - name: Update RSS Feed
              run: python scripts/rss/main.py

            - name: Commit
              run: |
                  git config --global user.email "actions@github.com"
                  git config --global user.name "GitHub Actions"
                  git pull
                  git add website/rss.xml
                  git commit -m "chore: update rss feed"
                  git push
